# Generated by Django 3.1.3 on 2020-12-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_notification', '0001_initial'),
        ('accounts', '0002_auto_20201205_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('profile_description', models.TextField()),
                ('establishment_date', models.DateField()),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('company_type', models.CharField(blank=True, choices=[('FINTECH', 'FINTECH'), ('BIOTECH', 'BIOTECH'),
                 ('MEDTECH', 'MEDTECH'), ('FOODTECH', 'FOODTECH'), ('AUTOMATIVE', 'AUTOMATIVE'), ('SW', 'SW'),
                 ('HW', 'HW'), ('UNSPECIFIED', 'UNSPECIFIED')], default='UNSPECIFIED', max_length=50, null=True)),
                ('company_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_description', models.TextField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('job_scope', models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PART', 'PART'),
                 ('INTER', 'INTER'), ('STUDENT', 'STUDENT'), ('UNSPECIFIED', 'UNSPECIFIED')], default='UNSPECIFIED',
                 max_length=50, null=True)),
                ('job_URL', models.URLField()),
                ('job_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 to='user_notification.jobtype')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchJob.company')),
                ('job_city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 to='user_notification.jobcity')),
            ],
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(blank=True, choices=[('APPLIED', 'APPLIED'),
                 ('NOT_APPLIED', 'NOT_APPLIED'), ('UNSPECIFIED', 'UNSPECIFIED')], default='UNSPECIFIED', max_length=50,
                 null=True)),
                ('user_account_id', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='accounts.UserAccount')),
                ('job_post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 to='searchJob.jobpost')),
            ],
        ),
    ]
