# Generated by Django 3.1.4 on 2020-12-17 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searchJob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='user_account_id',
            field=models.ForeignKey(blank=True,
                                    default=1,
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
