# Generated by Django 3.1.4 on 2020-12-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchJob', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='compamy_url',
            new_name='company_url',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='JobType_id',
            new_name='job_type_id',
        ),
        migrations.RenameField(
            model_name='userapplication',
            old_name='jobPost_id',
            new_name='job_post_id',
        ),
        migrations.RenameField(
            model_name='userapplication',
            old_name='UserAccount_id',
            new_name='user_account_id',
        ),
    ]
