# Generated by Django 3.1.3 on 2020-12-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('profile_description', models.TextField()),
                ('establishment_date', models.DateField()),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('company_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=1, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('user_birth_date', models.DateField()),
            ],
        ),
    ]
