# Generated by Django 3.1.3 on 2020-12-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='UserAccount',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='UserAccount',
            name='gender',
            field=models.CharField(blank=True,
                                   choices=[('M', 'Male'), ('F', 'Female'),
                                            ('NB', 'Nonbinary'), ('U', 'Unspecified')],
                                   default='U', max_length=2, null=True),
        ),
    ]
