# Generated by Django 3.1.4 on 2020-12-20 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[
                    ('M', 'Male'),
                    ('F', 'Female'),
                    ('NB', 'Nonbinary'),
                    ('U', 'Unspecified')], default='U', max_length=2)),
                ('contact_number', models.CharField(
                    blank=True, max_length=12, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='useraccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
