# Generated by Django 3.1.4 on 2020-12-17 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20201205_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_birth_date',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(blank=True,
                                       null=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       related_name='useraccount',
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'),
                                            ('F', 'Female'),
                                            ('NB', 'Nonbinary'),
                                            ('U', 'Unspecified')],
                                   default='U', max_length=2),
        ),
    ]
