# Generated by Django 3.1.4 on 2020-12-14 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20201213_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(blank=True,
                                       null=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       related_name='useraccount',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
