# Generated by Django 3.1.4 on 2020-12-20 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCity',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('job_city_name', models.CharField(max_length=20)), ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type_name', models.CharField(max_length=20)), ],
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_message', models.TextField()),
                ('alert_frequency', models.CharField(max_length=20)),
                ('job_alert_type', models.CharField(max_length=50)),
                ('job_alert_scope', models.CharField(max_length=50)),
                ('job_alert_city', models.CharField(max_length=50)),
                ('job_alert_company_name', models.CharField(max_length=20)),
                ('user_account_id', models.ForeignKey(blank=True, default=1, null=True,
                                                      on_delete=django.db.models.deletion.CASCADE,
                                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
