# Generated by Django 3.1.3 on 2020-12-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20201205_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_message', models.TextField()),
                ('alert_frequency', models.CharField(max_length=20)),
                ('job_alert_type', models.CharField(max_length=50)),
                ('job_alert_scope', models.CharField(max_length=50)),
                ('job_alert_city', models.CharField(max_length=50)),
                ('job_alert_company_name', models.CharField(max_length=20)),
                ('UserAccount_id', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
        ),
    ]
