# Generated by Django 3.1.4 on 2020-12-27 16:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobalert',
            name='alert_frequency',
        ),
        migrations.RemoveField(
            model_name='jobalert',
            name='alert_message',
        ),
        migrations.AddField(
            model_name='jobalert',
            name='frequency_in_days',
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='last_check_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='job_alert_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='job_alert_company_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='job_alert_scope',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PART', 'PART'), ('INTER', 'INTER'),
                                                        ('STUDENT', 'STUDENT'), ('UNSPECIFIED', 'UNSPECIFIED')],
                                   default='UNSPECIFIED', max_length=50, null=True),
        ),
    ]
